<a href="https://colab.research.google.com/github/joaompais-rgb/Data_Cleaning_pandas/blob/main/Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"

In [4]:
df_shark_attacks = pd.read_excel(url)

In [5]:
df_shark_attacks.shape

(7125, 23)

In [6]:
df_shark_attacks.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [7]:
df_shark_attacks.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7125 entries, 0 to 7124
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7125 non-null   object
 1   Year            7123 non-null   float64
 2   Type            7107 non-null   object
 3   Country         7075 non-null   object
 4   State           6638 non-null   object
 5   Location        6558 non-null   object
 6   Activity        6542 non-null   object
 7   Name            6907 non-null   object
 8   Sex             6547 non-null   object
 9   Age             4131 non-null   object
 10  Injury          7089 non-null   object
 11  Fatal Y/N       6564 non-null   object
 12  Time            3598 non-null   object
 13  Species         3994 non-null   object
 14  Source          7105 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.3+ MB

In [8]:
df_shark_attacks.nunique()

Date              6159
Year               261
Type                14
Country            257
State              956
Location          4662
Activity          1617
Name              5828
Sex                 12
Age                252
Injury            4229
Fatal Y/N           12
Time               493
Species           1772
Source            5447
pdf               6789
href formula      6784
href              6776
Case Number       6777
Case Number.1     6775
original order    6797
Unnamed: 21          1
Unnamed: 22          2
dtype: int64

In [9]:
df_shark_attacks. head ().T

,0,1,2,3,4
Date,18th September,16th September,14th September,13th September,7th September
Year,2026.0,2026.0,2026.0,2026.0,2026.0
Type,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked
Country,Australia,Canada,Bahamas,Australia,USA
State,Western Australia,Quebec,Bimini,Western Australia,Hawaii
Location,Sorrento Beach Perth,Off the coast of Perce Le Bilbo dive site,Bimini Island,Geraldton,Honolulu
Activity,Swimming,Diving,Swimming,Surfing,Surfing
Name,Greg O'Neil,Unknown Male,Unknown Austrian Tourist,Mel Ismail,Wants to remain anonymous
Sex,M,M,F,M,M
Age,63,?,37,50's,24
Injury,Body not recovered,Injuries to chest shoulder and back,Serious injuries to right ankle,Foot lost in attack,Scrapes on inside of legs
Fatal Y/N,Y,N,N,N,N
Time,1015hrs,1030hrs,1730hrs,0945hrs,1640hrs
Species,Great White Shark 6m (20ft),Great White Shark,Unknown,Unknown,Tiger Shark suspected
Source,Keith Cowley: Kevin McMurray Trackingsharks.co...,Keith Cowley: Kevin McMurray Trackingsharks.co...,Kevin McMurray Trackingsharks.com: Keith Cowley,Simon De Marchi,Keith Cowley
pdf,NaN,NaN,NaN,NaN,NaN
href formula,NaN,NaN,NaN,NaN,NaN
href,NaN,NaN,NaN,NaN,NaN
Case Number,NaN,NaN,NaN,NaN,NaN
Case Number.1,NaN,NaN,NaN,NaN,NaN
original order,NaN,NaN,NaN,NaN,NaN
Unnamed: 21,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,NaN,NaN,NaN,NaN,NaN

In [10]:
df_shark_attacks. tail ()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
7120,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7121,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7122,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7123,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7124,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [11]:
len(df_shark_attacks) - df_shark_attacks.count()

Date                 0
Year                 2
Type                18
Country             50
State              487
Location           567
Activity           583
Name               218
Sex                578
Age               2994
Injury              36
Fatal Y/N          561
Time              3527
Species           3131
Source              20
pdf                326
href formula       331
href               329
Case Number        327
Case Number.1      328
original order     326
Unnamed: 21       7124
Unnamed: 22       7123
dtype: int64

In [12]:
len(df_shark_attacks["Age"])

7125

- Cambiar  en columna 'Year' de float a int
- Limpiar columna 'Edad', cambiar de objet a int

In [13]:
new_df_shark_attacks = df_shark_attacks[['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species '].copy()]
new_df_shark_attacks.head().T

,0,1,2,3,4
Date,18th September,16th September,14th September,13th September,7th September
Year,2026.0,2026.0,2026.0,2026.0,2026.0
Type,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked
Country,Australia,Canada,Bahamas,Australia,USA
State,Western Australia,Quebec,Bimini,Western Australia,Hawaii
Location,Sorrento Beach Perth,Off the coast of Perce Le Bilbo dive site,Bimini Island,Geraldton,Honolulu
Activity,Swimming,Diving,Swimming,Surfing,Surfing
Name,Greg O'Neil,Unknown Male,Unknown Austrian Tourist,Mel Ismail,Wants to remain anonymous
Sex,M,M,F,M,M
Age,63,?,37,50's,24
Injury,Body not recovered,Injuries to chest shoulder and back,Serious injuries to right ankle,Foot lost in attack,Scrapes on inside of legs
Fatal Y/N,Y,N,N,N,N
Time,1015hrs,1030hrs,1730hrs,0945hrs,1640hrs
Species,Great White Shark 6m (20ft),Great White Shark,Unknown,Unknown,Tiger Shark suspected

DATE = PARA PERCIBIR UNA RELACION DE TEMPORADAS DE ATAQUES

In [14]:
new_df_shark_attacks.shape

(7125, 14)

### Valores em falta

### Valores ausentes

**Preguntas**

* ¿Qué columnas tienen más valores ausentes?
* ¿Hay filas completamente vacías?
* ¿Las columnas que necesitamos (Type, Country, Activity, Year, Fatal) tienen muchos valores ausentes?

**Notas**

* Hay ___ filas completamente vacías al final del archivo. Se eliminan.
* Las columnas con más valores ausentes son ___ y ___, que no utilizamos en el análisis.
* Activity tiene ___ valores ausentes (___%). Estos casos se clasifican como **"Unknown"** en lugar de eliminarse, para no perder el registro del país.
* Country tiene ___ valores ausentes. Estos casos se clasifican como **"Unknown"** en lugar de eliminarse, para no perder el registro del país.

### Notas

* Cada fila corresponde a un ataque de tiburón registrado.
* Las columnas **pdf, href formula y href** son nombres y enlaces de los informes en PDF de cada caso. No contienen información sobre el ataque.
* **original order** es la numeración interna del sitio web.
* **Unnamed: 21** y **Unnamed: 22** son columnas sin encabezado, con 1 y 2 valores en más de 6000 filas: son notas sueltas en el archivo de Excel.
* **Decisión:** estas 8 columnas se eliminarán durante la limpieza.
* **Age** está almacenada como texto porque contiene valores como **"30s"** o **"teen"**.

NEGOCIO = ESCUELA DE SURF SEGURA
- Saber la mayor y menor cantidad de ataques segun:
PAIS, ESTADO, LOCALIDAD
SEASON ATTACK
HORA DEL DIA

In [19]:
df_shark_attacks.isna().sum().sort_values(ascending=False)

Unnamed: 21       7124
Unnamed: 22       7123
Time              3527
Species           3131
Age               2994
Activity           583
Sex                578
Location           567
Fatal Y/N          561
State              487
href formula       331
href               329
Case Number.1      328
Case Number        327
pdf                326
original order     326
Name               218
Country             50
Injury              36
Source              20
Type                18
Year                 2
Date                 0
dtype: int64

In [20]:
(len(df_shark_attacks) - df_shark_attacks.count()).sort_values(ascending=False)

Unnamed: 21       7124
Unnamed: 22       7123
Time              3527
Species           3131
Age               2994
Activity           583
Sex                578
Location           567
Fatal Y/N          561
State              487
href formula       331
href               329
Case Number.1      328
Case Number        327
pdf                326
original order     326
Name               218
Country             50
Injury              36
Source              20
Type                18
Year                 2
Date                 0
dtype: int64

In [21]:
print("Filas completamente vacías:", df_shark_attacks.isna().all(axis=1).sum())

Filas completamente vacías: 0

In [22]:
def clean_column_names(df):
    df = df.copy()
    df.columns = df.columns.str.strip()
    df = df.rename(columns={"Fatal Y/N": "Fatal", "Fatal (Y/N)": "Fatal"})
    return df

new_df_shark_attacks = clean_column_names(df_shark_attacks)
list(new_df_shark_attacks.columns)

['Date',
 'Year',
 'Type',
 'Country',
 'State',
 'Location',
 'Activity',
 'Name',
 'Sex',
 'Age',
 'Injury',
 'Fatal',
 'Time',
 'Species',
 'Source',
 'pdf',
 'href formula',
 'href',
 'Case Number',
 'Case Number.1',
 'original order',
 'Unnamed: 21',
 'Unnamed: 22']

In [24]:
columns_to_keep = [
    "Date", "Year", "Type", "Country", "State", "Location",
    "Activity", "Sex", "Age", "Injury", "Fatal", "Time", "Species",
]
new_df_shark_attacks = new_df_shark_attacks[columns_to_keep].copy()
new_df_shark_attacks.shape

(7125, 13)

In [25]:
before = len(new_df_shark_attacks)
new_df_shark_attacks = new_df_shark_attacks.dropna(how="all")
print("Filas borradas:", before - len(new_df_shark_attacks))

Filas borradas: 0