<a href="https://colab.research.google.com/github/joaompais-rgb/Data_Cleaning_pandas/blob/main/Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"

In [ ]:
df_shark_attacks = pd.read_excel(url)

In [ ]:
df_shark_attacks.shape

(7125, 23)

In [ ]:
df_shark_attacks.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [ ]:
df_shark_attacks.info ()

In [ ]:
df_shark_attacks.nunique()

In [ ]:
df_shark_attacks. head ().T

,0,1,2,3,4
Date,18th September,16th September,14th September,13th September,7th September
Year,2026.0,2026.0,2026.0,2026.0,2026.0
Type,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked
Country,Australia,Canada,Bahamas,Australia,USA
State,Western Australia,Quebec,Bimini,Western Australia,Hawaii
Location,Sorrento Beach Perth,Off the coast of Perce Le Bilbo dive site,Bimini Island,Geraldton,Honolulu
Activity,Swimming,Diving,Swimming,Surfing,Surfing
Name,Greg O'Neil,Unknown Male,Unknown Austrian Tourist,Mel Ismail,Wants to remain anonymous
Sex,M,M,F,M,M
Age,63,?,37,50's,24
Injury,Body not recovered,Injuries to chest shoulder and back,Serious injuries to right ankle,Foot lost in attack,Scrapes on inside of legs
Fatal Y/N,Y,N,N,N,N
Time,1015hrs,1030hrs,1730hrs,0945hrs,1640hrs
Species,Great White Shark 6m (20ft),Great White Shark,Unknown,Unknown,Tiger Shark suspected
Source,Keith Cowley: Kevin McMurray Trackingsharks.co...,Keith Cowley: Kevin McMurray Trackingsharks.co...,Kevin McMurray Trackingsharks.com: Keith Cowley,Simon De Marchi,Keith Cowley
pdf,NaN,NaN,NaN,NaN,NaN
href formula,NaN,NaN,NaN,NaN,NaN
href,NaN,NaN,NaN,NaN,NaN
Case Number,NaN,NaN,NaN,NaN,NaN
Case Number.1,NaN,NaN,NaN,NaN,NaN
original order,NaN,NaN,NaN,NaN,NaN
Unnamed: 21,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_shark_attacks. tail ()

In [ ]:
len(df_shark_attacks) - df_shark_attacks.count()

In [ ]:
len(df_shark_attacks["Age"])

7125

- Cambiar  en columna 'Year' de float a int
- Limpiar columna 'Edad', cambiar de objet a int

In [ ]:
new_df_shark_attacks = df_shark_attacks[['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species '].copy()]
new_df_shark_attacks.head().T

,0,1,2,3,4
Date,18th September,16th September,14th September,13th September,7th September
Year,2026.0,2026.0,2026.0,2026.0,2026.0
Type,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked
Country,Australia,Canada,Bahamas,Australia,USA
State,Western Australia,Quebec,Bimini,Western Australia,Hawaii
Location,Sorrento Beach Perth,Off the coast of Perce Le Bilbo dive site,Bimini Island,Geraldton,Honolulu
Activity,Swimming,Diving,Swimming,Surfing,Surfing
Name,Greg O'Neil,Unknown Male,Unknown Austrian Tourist,Mel Ismail,Wants to remain anonymous
Sex,M,M,F,M,M
Age,63,?,37,50's,24
Injury,Body not recovered,Injuries to chest shoulder and back,Serious injuries to right ankle,Foot lost in attack,Scrapes on inside of legs
Fatal Y/N,Y,N,N,N,N
Time,1015hrs,1030hrs,1730hrs,0945hrs,1640hrs
Species,Great White Shark 6m (20ft),Great White Shark,Unknown,Unknown,Tiger Shark suspected

DATE = PARA PERCIBIR UNA RELACION DE TEMPORADAS DE ATAQUES

In [ ]:
new_df_shark_attacks.shape

(7125, 14)

NEGOCIO = ESCUELA DE SURF SEGURA
- Saber la mayor y menor cantidad de ataques segun:
PAIS, ESTADO, LOCALIDAD
SEASON ATTACK
HORA DEL DIA